name: python_app
run-name: ${{ github.actor }} an example of a workflow on event
on: [push]
jobs:
  do_unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -m unittest tests/test_StrategyParserXML.py
      
  deploy:
      needs: do_unittest
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
    
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
    
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        - name: Deploy to Nexus
          run: | 
            python -m pip install twine
            twine upload --repository-url http://localhost:8081/repository/xml_PARSER/ -u ${{ secrets.admin }} -p ${{ secrets.adminadmin }} --skip-existing dist/*